In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)

In [2]:
incident = pd.read_csv('../../../data/01-modified-data/SSDB/incident.csv')
shooter = pd.read_csv('../../../data/01-modified-data/SSDB/shooter.csv')
victim = pd.read_csv('../../../data/01-modified-data/SSDB/victim.csv')
weapon = pd.read_csv('../../../data/01-modified-data/SSDB/weapon.csv')

In [3]:
incident.head()

,Incident_ID,Sources,Number_News,Media_Attention,Reliability,Date,Quarter,School,City,State,School_Level,Location,Location_Type,During_School,Time_Period,First_Shot,Summary,Narrative,Situation,Targets,Accomplice,Hostages,Barricade,Officer_Involved,Bullied,Domestic_Violence,Gang_Related,Preplanned,Shots_Fired,Active_Shooter_FBI
0,20220620ILGRC,https://www.cbsnews.com/chicago/news/woman-and...,50,National,4,2022-06-20,Summer,Gresham School of Excellence,Chicago,IL,Elementary,Field (General),Outside on School Property,No,Night,01:00:00,3 people shot on elementary school field,100 shots were fired on the field of the eleme...,NaN,Both,No,No,No,No,No,No,NaN,No,100,No
1,20220613WAMAE,https://www.q13fox.com/news/deputies-arrest-15...,5,Local,4,2022-06-13,Summer,Mariner High School,Everett,WA,High,Parking Lot,Outside on School Property,No,After School,15:10:00,Shots fired in parking lot by teen during afte...,A 15-year-old male fired shots at two teens in...,Escalation of Dispute,Victims Targeted,No,No,No,No,No,No,NaN,No,99,No
2,20220610ALBYB,https://www.actionnews5.com/2022/06/10/student...,3,Local,4,2022-06-10,Summer,Byhalia High School,Byhalia,MS,High,Parking Lot,Outside on School Property,Yes,Morning Classes,10:30:00,Student fired gun in parking lot during dispute,Student (unidentified minor) fired shot during...,Escalation of Dispute,Victims Targeted,NaN,No,No,No,No,No,NaN,No,1,No
3,20220609ALWAG,https://www.live5news.com/2022/06/09/potential...,100,National,4,2022-06-09,Summer,Walnut Park Elementary School,Gadsden,AL,Elementary,Front of School,Outside on School Property,Yes,Morning Classes,09:30:00,Man fatally shot by SRO while trying to break-...,A 32-year-old man was fatally shot by a school...,Officer-Involved Shooting,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No
4,20220608ARLIL,https://www.kark.com/crime/lrpd-school-bus-hit...,5,National,4,2022-06-08,Summer,Little Rock School District Bus,Little Rock,AR,Other,School Bus,School Bus,Yes,Dismissal,16:01:00,Shots struck school bus driving student home,Shots struck a school bus. Driver and student ...,NaN,Both,NaN,No,No,No,No,No,NaN,No,99,No

In [4]:
shooter.head()

,incidentid,age,gender,race,schoolaffiliation,shooteroutcome,shooterdied,injury,chargesfiled,verdict,minorchargedadult,criminalhistory
0,20220620ILGRC,NaN,NaN,NaN,No Relation,Fled/Escaped,No,None,NaN,NaN,NaN,NaN
1,20220613WAMAE,15,Male,NaN,Student,Fled/Apprehended,No,None,"unlawful possession of a firearm, disturbing s...",NaN,NaN,NaN
2,20220610ALBYB,Teen,Male,NaN,Student,Fled/Apprehended,No,None,NaN,NaN,NaN,NaN
3,20220609ALWAG,NaN,NaN,NaN,Police Officer/SRO,Law Enforcement,No,None,NaN,NaN,NaN,NaN
4,20220608ARLIL,NaN,NaN,NaN,No Relation,Fled/Escaped,No,None,NaN,NaN,NaN,NaN

In [5]:
victim.head()

      incidentid   race   injury  gender schoolaffiliation age
0  20220620ILGRC    NaN  Wounded  Female       No Relation  34
1  20220620ILGRC    NaN  Wounded    Male       No Relation  16
2  20220620ILGRC    NaN  Wounded  Female       No Relation  17
3  20220609ALWAG  Black    Fatal    Male       No Relation  32
4  20220605INWEG    NaN  Wounded    Male               NaN  19

In [6]:
weapon.head()

      incidentid   weaponcaliber weapondetails weapontype
0  20220620ILGRC             NaN           NaN        NaN
1  20220613WAMAE             NaN           NaN    Handgun
2  20220610ALBYB             NaN           NaN    Handgun
3  20220609ALWAG  Service Weapon           NaN    Handgun
4  20220608ARLIL             NaN           NaN        NaN